const {chromium} = require('playwright');
const fs = require('fs');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({channel:'chrome', headless:true});
  const page = await browser.newPage({viewport:{width:1280,height:1500}});
  await page.route('https://www.bilibili.com/**', route => route.fulfill({contentType:'text/html',body:'<!doctype html><h1 class="video-title">测试视频</h1><div id="mount"></div>'}));
  await page.goto('https://www.bilibili.com/video/BVtest/');
  await page.evaluate(() => {
    window.calls = [];
    window.config = {enabled:true,dynamics:true,pinned:true,configured:true,mode:'fold',threshold:.6};
    window.chrome = {runtime:{onMessage:{addListener(fn){window.onMessage=fn;}},async sendMessage(m){
      if(m.type==='settings')return {ok:true,data:window.config};
      window.calls.push(m.state);return {ok:true,data:{prob:m.state.text.includes('普通')?.1:.9,kind:'ad',fold: m.state.text.includes('普通')?false:window.config.mode==='fold'}};
    }}};
    const mount = document.querySelector('#mount');
    mount.innerHTML = '<div class="bili-dyn-item" id="dyn"><div class="bili-dyn-item__header"><a class="bili-dyn-title__text" href="https://space.bilibili.com/123">steam情报局</a></div><div class="bili-dyn-item__body">优惠商品 购买链接</div><div class="bili-dyn-item__footer">分享 评论 点赞</div></div><div class="reply-item" id="old"><span class="top">置顶</span><div class="reply-content">领取优惠券</div></div><div class="reply-item" id="regular"><div class="reply-content">普通评论</div></div>';
    const comments = document.createElement('bili-comments');mount.append(comments);
    const sr = comments.attachShadow({mode:'open'});
    for (const [id,pin,text] of [['new',true,'购买新商品'],['notpin',false,'置顶']]) {
      const thread=document.createElement('bili-comment-thread-renderer');thread.id=id;thread.style.display='block';sr.append(thread);
      const tr=thread.attachShadow({mode:'open'});const main=document.createElement('bili-comment-renderer');tr.append(main);
      const mr=main.attachShadow({mode:'open'});mr.innerHTML=(pin?'<span id="top">置顶</span>':'')+'<div id="content"><bili-rich-text></bili-rich-text></div>';
      mr.querySelector('bili-rich-text').attachShadow({mode:'open'}).innerHTML='<span>'+text+'</span>';
    }
  });
  await page.addScriptTag({content:fs.readFileSync('content.js','utf8')});
  await page.waitForTimeout(1800);
  assert.equal(await page.evaluate(()=>calls.length),3,'dynamic + old pin + shadow pin only');
  assert.equal(await page.locator('#dyn').evaluate(e=>e.style.display),'none');
  assert.equal(await page.locator('bili-breeze-ui').count(),3);
  assert.match(await page.locator('bili-breeze-ui').first().locator('.box').innerText(),/steam情报局.*广告.*90%/);
  await page.getByRole('button',{name:'展开内容'}).first().click();
  assert.notEqual(await page.locator('#dyn').evaluate(e=>e.style.display),'none');
  await page.waitForTimeout(300);
  assert.equal(await page.locator('#dyn').evaluate(e=>e.getAnimations().length),0);
  const box=page.locator('bili-breeze-ui').first().locator('.box');
  assert((await box.boundingBox()).width < 420, 'label stays compact on a wide viewport');
  await page.getByRole('button',{name:'收起'}).click();
  assert(await page.locator('#dyn').evaluate(e=>e.getAnimations().length)>0,'collapse animates');
  await page.waitForTimeout(300);
  assert.equal(await page.locator('#dyn').evaluate(e=>e.style.display),'none');
  await page.getByRole('button',{name:'展开内容'}).first().click();
  await page.getByRole('button',{name:'收起'}).click();
  await page.waitForTimeout(300);
  assert.equal(await page.locator('#dyn').evaluate(e=>e.style.display),'none','rapid toggle ends collapsed');
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.getByRole('button',{name:'展开内容'}).first().click();
  assert.equal(await page.locator('#dyn').evaluate(e=>e.getAnimations().length),0,'reduced motion skips animation');
  await page.getByRole('button',{name:'收起'}).click();
  await page.emulateMedia({reducedMotion:'no-preference'});
  await page.evaluate(()=>{config.enabled=false;onMessage({type:'settingsChanged'});});
  await page.waitForTimeout(400);
  assert.equal(await page.locator('bili-breeze-ui').count(),0);
  assert.equal(await page.locator('#dyn').evaluate(e=>e.style.display),'');
  await page.evaluate(()=>{config.enabled=true;config.mode='fold';onMessage({type:'settingsChanged'});});
  await page.waitForTimeout(1100);
  assert.equal(await page.locator('#dyn').evaluate(e=>e.style.display),'none');
  const before=await page.evaluate(()=>calls.length);
  await page.evaluate(()=>{document.querySelector('#dyn .bili-dyn-item__body').textContent='普通动态';});
  await page.waitForTimeout(700);
  assert.equal(await page.evaluate(()=>calls.length),before+1,'reused dynamic content rechecked');
  assert.equal(await page.locator('bili-breeze-ui').count(),2);
  await page.evaluate(()=>{history.pushState({},'', '/opus/123');});
  await page.waitForTimeout(2300);
  assert.equal(await page.locator('bili-breeze-ui').count(),0,'pin removed outside video page');
  await page.evaluate(()=>{
    config.mode='fold';
    document.querySelector('#mount').innerHTML='<div style="height:1800px"></div><div class="bili-dyn-item" id="ahead"><div class="bili-dyn-item__body">屏幕外广告</div></div><div style="height:9000px"></div><div class="bili-dyn-item" id="far"><div class="bili-dyn-item__body">远处广告</div></div>';
    onMessage({type:'settingsChanged'});
  });
  await page.waitForTimeout(1000);
  assert.equal(await page.locator('#ahead').evaluate(e=>e.style.display),'none','offscreen card folded before scrolling');
  assert.equal(await page.evaluate(()=>calls.some(c=>c.text==='远处广告')),false,'bounded lookahead');
  console.log('PASS: offscreen detection before scrolling and bounded lookahead');
  await page.evaluate(()=>{config.mode='label';onMessage({type:'settingsChanged'});});
  await page.waitForTimeout(800);
  assert.notEqual(await page.locator('#ahead').evaluate(e=>e.style.display),'none','author policy change restores collapsed content');
  await page.evaluate(()=>{document.querySelector('#mount').innerHTML='<div class="bili-dyn-item"><div class="bili-dyn-item__body">游戏提名新闻<div class="bili-dyn-content__orig">互动抽奖 转发关注抽1人</div></div></div>';});
  await page.waitForTimeout(800);
  const separated=await page.evaluate(()=>calls.find(c=>c.forwardedText));
  assert.equal(separated.originalText,'游戏提名新闻');assert.match(separated.forwardedText,/互动抽奖/);
  console.log('PASS: old/new pinned detection, ordinary comment exclusion, nested rich text, fold/restore, settings update, reused nodes, SPA navigation');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
