const {chromium}=require('playwright');
const fs=require('fs'),assert=require('node:assert/strict'),path=require('path');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const page=await browser.newPage({colorScheme:'dark',viewport:{width:380,height:600}});
 const root=path.resolve('.');
 await page.route('https://fixture.test/**',r=>{const name=new URL(r.request().url()).pathname.slice(1)||'popup.html';r.fulfill({body:fs.readFileSync(path.join(root,name)),contentType:name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':'text/html'});});
 await page.addInitScript(()=>{
  const get=()=>JSON.parse(localStorage.getItem('settings')||'{}');
  window.chrome={permissions:{request:async()=>true},storage:{local:{get:async d=>({...d,...get()}),set:async v=>localStorage.setItem('settings',JSON.stringify({...get(),...v}))}},runtime:{sendMessage:async m=>m.type==='lookupAuthor'?{ok:true,data:{users:m.query==='重名'?[{uid:'2',name:'重名'},{uid:'3',name:'重名'}]:[{uid:'123',name:'-LKs-'}]}}:({ok:true,data:{enabled:true,dynamics:true,pinned:true,mode:'label',threshold:.6,...get()}})}};
 });
 await page.goto('https://fixture.test/popup.html');
 await page.waitForFunction(()=>document.querySelector('#enabled').checked);
 await page.locator('#foldIncidental').check();
 await page.waitForFunction(()=>JSON.parse(localStorage.settings).foldIncidental===true);
 await page.locator('#fold_recruitment').check();
 await page.waitForFunction(()=>JSON.parse(localStorage.settings).foldCategories.includes('recruitment'));
 await page.reload();await page.waitForFunction(()=>document.querySelector('#fold_recruitment').checked);
 assert.equal(await page.locator('body').evaluate(e=>getComputedStyle(document.documentElement).backgroundColor),'rgb(23, 26, 32)');
 await page.emulateMedia({colorScheme:'light'});
 assert.equal(await page.locator('body').evaluate(e=>getComputedStyle(document.documentElement).backgroundColor),'rgb(245, 247, 250)');
 await page.getByRole('tab',{name:'API',exact:true}).click();
 await page.locator('#provider').selectOption('custom');
 await page.locator('#apiUrl').fill('https://example.test/v1/chat/completions');
 await page.locator('#apiModel').fill('test-model');await page.locator('#apiKey').fill('test-only');
 await page.getByRole('button',{name:'保存 API 设置'}).click();
 await page.waitForFunction(()=>JSON.parse(localStorage.settings).apiUrl==='https://example.test/v1/chat/completions');
 await page.reload();await page.waitForFunction(()=>document.querySelector('#apiModel').value==='test-model');
 assert.equal(await page.locator('#fold_recruitment').isChecked(),true);
 await page.getByRole('tab',{name:'名单',exact:true}).click();
 await page.locator('#enhancedListQuery').fill('123');await page.locator('#enhancedListQuery').press('Enter');
 await page.waitForFunction(()=>JSON.parse(localStorage.settings).enhancedList[0].name==='-LKs-');
 assert((await page.locator('#enhancedList .author-entry').boundingBox()).height<65,'compact author row');
 await page.screenshot({path:'../popup-lists-1.0.0.png',fullPage:true});
 await page.reload();await page.waitForFunction(()=>document.querySelector('#enhancedList').textContent.includes('UID 123'));
 await page.getByRole('tab',{name:'名单',exact:true}).click();
 await page.locator('#whitelistQuery').fill('不是UID');await page.locator('#whitelistAdd').click();
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.settings).whitelist?.length||0),0);
 await page.locator('#whitelistQuery').fill('456');await page.locator('#whitelistAdd').click();
 await page.waitForFunction(()=>JSON.parse(localStorage.settings).whitelist[0].uid==='456');
 await page.waitForFunction(()=>document.querySelector('#whitelistStatus').textContent.includes('名字获取失败'));
 await page.locator('#whitelist').getByRole('button',{name:'移除'}).click();
 await page.waitForFunction(()=>JSON.parse(localStorage.settings).whitelist.length===0);
 assert.equal(await page.locator('#listTarget').count(),0);
 assert.equal(await page.locator('#blacklist').count(),0);
 assert.equal(await page.locator('[role="switch"]').count(),9);
 assert.equal(await page.locator('[role=tabpanel]:visible').count(),1);
 await page.getByRole('tab',{name:'过滤',exact:true}).click();
 await page.getByRole('tab',{name:'过滤',exact:true}).press('ArrowRight');
 assert.equal(await page.locator('#tab-lists').getAttribute('aria-selected'),'true');
 await page.getByRole('tab',{name:'API',exact:true}).click();
 await page.locator('#apiModel').fill('unsaved-model');
 await page.getByRole('tab',{name:'过滤',exact:true}).click();
 await page.getByRole('tab',{name:'API',exact:true}).click();
 assert.equal(await page.locator('#apiModel').inputValue(),'unsaved-model');
 await page.locator('#apiModel').fill('unsaved-model');
 assert((await page.locator('body').boundingBox()).height<=580,'custom API fits within 580 CSS pixels');
 assert.equal(await page.locator('#panel-api').evaluate(e=>e.scrollHeight<=e.clientHeight),true);
 await page.screenshot({path:'../popup-api-1.0.0.png',fullPage:true});
 await page.getByRole('tab',{name:'过滤',exact:true}).click();
 await page.emulateMedia({colorScheme:'dark'});await page.screenshot({path:'../popup-1.0.0.png',fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 assert.equal(await page.locator('html').evaluate(e=>e.getBoundingClientRect().width),380);
 for(const name of ['过滤','名单','API']){
  await page.getByRole('tab',{name,exact:true}).click();
  const size=await page.locator('body').boundingBox();assert.equal(size.height,580);assert.equal(size.width,380);
  const panel=await page.locator('[role=tabpanel]:visible').boundingBox(),footer=await page.locator('footer').boundingBox();assert(panel.y+panel.height<=footer.y,'panel must not overlap footer');
 }
 await page.getByRole('tab',{name:'过滤',exact:true}).click();
 assert((await page.locator('body').boundingBox()).height<=580,'filter fits within 580 CSS pixels, including footer');
 assert.equal(await page.locator('#panel-filter').evaluate(e=>e.scrollHeight<=e.clientHeight),true);
 await page.locator('#openRules').click();
 assert.equal(await page.locator('#adThresholdNumber').inputValue(),'70');
 await page.locator('#adThresholdNumber').fill('75');await page.locator('#adThresholdNumber').press('Tab');
 await page.waitForFunction(()=>JSON.parse(localStorage.settings).adThreshold===75);
 assert.equal(await page.locator('#adThresholdRange').inputValue(),'75');
 await page.locator('#ratioThresholdRange').fill('45');await page.locator('#ratioThresholdRange').dispatchEvent('change');
 await page.waitForFunction(()=>JSON.parse(localStorage.settings).ratioThreshold===45);
 assert.equal(await page.locator('#ratioThresholdNumber').inputValue(),'45');
 await page.locator('#customPrompt').fill('  游戏官方号宣传新活动也算广告  ');await page.locator('#customPrompt').press('Tab');
 await page.waitForFunction(()=>JSON.parse(localStorage.settings).customPrompt==='游戏官方号宣传新活动也算广告');
 await page.reload();await page.locator('#openRules').click();
 assert.equal(await page.locator('#customPrompt').inputValue(),'游戏官方号宣传新活动也算广告');
 const ruleBox=await page.locator('#filterRules').boundingBox(),footBox=await page.locator('footer').boundingBox();assert(ruleBox.y+ruleBox.height<=footBox.y);
 await page.screenshot({path:'../rules-1.0.0.png',fullPage:true});
 await page.locator('#backRules').click();
 await page.setViewportSize({width:380,height:580});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight),true,'no page scrollbar in compact popup');
 await page.evaluate(()=>{const s=JSON.parse(localStorage.settings);s.whitelist=[];s.enhancedList=[];localStorage.settings=JSON.stringify(s);});
 await page.reload();await page.getByRole('tab',{name:'名单',exact:true}).click();
 assert.equal(await page.locator('#panel-lists').evaluate(e=>e.scrollHeight<=e.clientHeight),true,'short lists do not scroll');
 await page.evaluate(()=>{const s=JSON.parse(localStorage.settings);s.whitelist=Array.from({length:30},(_,i)=>({uid:String(i+1),name:'用户'+i}));localStorage.settings=JSON.stringify(s);});
 await page.reload();await page.getByRole('tab',{name:'名单',exact:true}).click();
 await page.waitForFunction(()=>document.querySelectorAll('.author-entry').length===30);
 assert.equal(await page.locator('#panel-lists').evaluate(e=>e.scrollHeight>e.clientHeight),true,'long lists remain accessible by scrolling');
 await page.evaluate(()=>{const s=JSON.parse(localStorage.settings);s.whitelist=[null,{uid:'7',name:'有效用户'}];s.enhancedList=[{uid:'8',name:'谨慎用户'}];localStorage.settings=JSON.stringify(s);});
 await page.reload();await page.getByRole('tab',{name:'名单',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#whitelist').textContent.includes('有效用户')&&document.querySelector('#enhancedList').textContent.includes('谨慎用户'));
 assert.equal(await page.locator('#whitelist .author-entry').count(),1,'null entry skipped, lists still render');
 console.log('PASS popup: auto-save persists after closing/reopening, dark/light colors, custom API save/reload');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});


